<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="aragarwa01-mac" failures="2" tests="2" name="Default test(failed)" time="0.04" errors="0" timestamp="2021-08-04T20:17:39 IST">
  <testcase classname="Grouping.TestNgRetryDemo" name="test3" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Grouping.TestNgRetryDemo.test3(TestNgRetryDemo.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Grouping.TestNgRetryDemo" name="test2" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at Grouping.TestNgRetryDemo.test2(TestNgRetryDemo.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="Grouping.TestNgRetryDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
